### ISSUE TITLE
Username is case-sensitive

### ISSUE THREAD

**Issue by Nightcaat** [blobs-io/blobs.live#7]
I can't log in as "nightcat" and I assume that someone would be able to register as "nightcat" so please fix that!

**Comment by y21** [comment]
You can't login? What error does it give to you?

**Comment by DatNightcat** [comment]
It just says "Incorrect username or password."

**Comment by y21** [comment]
Oh, I totally got it wrong. I know what you mean. Good idea!

**Comment by y21** [comment]
Fixed in https://github.com/blobs-io/blobs.io/commit/daa0ec3611c151bad454948f5b78797a9bb52194; it now checks if the username already exists, no matter if the original name has different capitalization.
In other words: nobody will be able to register as `nightcat` or `NIGhtCaT`.

**Comment by Nightcaat** [comment]
Registration works as intended, but I can still only log in as `Nightcat`.
